name: Build and Publish Docker Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 10
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: Log into registry
      run: 
        docker logout --help
        docker logout https://registry-1.docker.io/v2
    - name: Create and push Docker images
      run: cd microservice-kubernetes-demo && sh ./docker-build.sh
